export const WC2026_TEAMS = [
  "Argentina",
  "Australia",
  "Belgium",
  "Bolivia",
  "Brazil",
  "Cameroon",
  "Canada",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Ecuador",
  "Egypt",
  "England",
  "France",
  "Germany",
  "Ghana",
  "Honduras",
  "Hungary",
  "Indonesia",
  "Iran",
  "Italy",
  "Ivory Coast",
  "Japan",
  "Kenya",
  "Mali",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Panama",
  "Paraguay",
  "Peru",
  "Portugal",
  "Qatar",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Switzerland",
  "Trinidad and Tobago",
  "Ukraine",
  "United States",
  "Uruguay",
] as const;

export type WC2026Team = (typeof WC2026_TEAMS)[number];

export const TEAM_TO_FLAG_CODE: Record<string, string> = {
  Argentina: "AR",
  Australia: "AU",
  Belgium: "BE",
  Bolivia: "BO",
  Brazil: "BR",
  Cameroon: "CM",
  Canada: "CA",
  Chile: "CL",
  Colombia: "CO",
  "Costa Rica": "CR",
  Croatia: "HR",
  Ecuador: "EC",
  Egypt: "EG",
  England: "GB-ENG",
  France: "FR",
  Germany: "DE",
  Ghana: "GH",
  Honduras: "HN",
  Hungary: "HU",
  Indonesia: "ID",
  Iran: "IR",
  Italy: "IT",
  "Ivory Coast": "CI",
  Japan: "JP",
  Kenya: "KE",
  Mali: "ML",
  Mexico: "MX",
  Morocco: "MA",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Nigeria: "NG",
  Panama: "PA",
  Paraguay: "PY",
  Peru: "PE",
  Portugal: "PT",
  Qatar: "QA",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Slovenia: "SI",
  "South Africa": "ZA",
  "South Korea": "KR",
  Spain: "ES",
  Switzerland: "CH",
  "Trinidad and Tobago": "TT",
  Ukraine: "UA",
  "United States": "US",
  Uruguay: "UY",
};

export const STAGE_LABELS: Record<string, string> = {
  GROUP: "Group Stage",
  ROUND_OF_32: "Round of 32",
  ROUND_OF_16: "Round of 16",
  QUARTER_FINAL: "Quarter Finals",
  SEMI_FINAL: "Semi Finals",
  THIRD_PLACE: "Third Place",
  FINAL: "Final",
};

export const STAGE_ORDER: Record<string, number> = {
  GROUP: 1,
  ROUND_OF_32: 2,
  ROUND_OF_16: 3,
  QUARTER_FINAL: 4,
  SEMI_FINAL: 5,
  THIRD_PLACE: 6,
  FINAL: 7,
};
